#!/bin/bash
# Download the CUDA repository package
sudo bash
sudo wget https://developer.download.nvidia.com/compute/cuda/12.3.1/local_installers/cuda-repo-debian12-12-3-local_12.3.1-545.23.08-1_amd64.deb

# Install the CUDA repository key
sudo dpkg -i cuda-repo-debian12-12-3-local_12.3.1-545.23.08-1_amd64.deb ||
sudo cp /var/cuda-repo-debian12-12-3-local/cuda-*-keyring.gpg /usr/share/keyrings

# Add the CUDA repository to your sources list
sudo add-apt-repository contrib

# Update the package list
sudo apt-get update

# Install the CUDA toolkit and drivers
sudo apt-get install -y cuda-toolkit-12-3 -y
sudo apt-get install -y cuda-drivers -y
